name: base
channels:
  - conda-forge
dependencies:
  - pip=22.1.2=pyhd8ed1ab_0
  - pip:
      - anyio==3.6.2
      - appdirs==1.4.4
      - appnope==0.1.3
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arpeggio==2.0.0
      - asttokens==2.2.1
      - attrs==22.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.11.1
      - bitmath==1.3.3.1
      - bitstring==3.1.9
      - bleach==5.0.1
      - blessed==1.17.12
      - bpylist2==3.0.2
      - bqplot==0.11.0
      - click==8.1.3
      - commonmark==0.9.1
      - debugpy==1.6.4
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - entrypoints==0.4
      - executing==1.2.0
      - fastjsonschema==2.16.2
      - importlib-metadata==5.1.0
      - ipykernel==6.4.2
      - ipynb==0.5.1
      - ipython==7.34.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.2
      - jedi==0.18.1
      - jinja2==2.11.3
      - joblib==1.2.0
      - jsonschema==4.17.3
      - jupyter-client==7.4.8
      - jupyter-core==5.0.0
      - jupyter-server==1.13.2
      - jupyterlab-pygments==0.2.2
      - jupyterlab-widgets==1.1.1
      - mako==1.1.6
      - markupsafe==2.1.1
      - matplotlib-inline==0.1.6
      - mistune==0.8.4
      - more-itertools==8.14.0
      - nbclassic==0.4.8
      - nbclient==0.7.2
      - nbconvert==5.6.1
      - nbformat==4.4.0
      - nbinteract==0.2.6
      - nest-asyncio==1.5.6
      - nltk==3.7
      - notebook==6.5.2
      - notebook-shim==0.2.2
      - objexplore==1.6.3
      - osxmetadata==0.99.38
      - osxphotos==0.51.7
      - packaging==21.3
      - pandas==1.5.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathvalidate==2.5.2
      - pearl==2.3.8
      - perl==1.0.0
      - pexpect==4.8.0
      - photoscript==0.1.5
      - pickleshare==0.7.5
      - platformdirs==2.5.4
      - prometheus-client==0.15.0
      - prompt-toolkit==3.0.31
      - psutil==5.9.4
      - ptpython==3.0.20
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-applescript==1.0.2
      - pyexiftool==0.5.4
      - pygments==2.13.0
      - pyobjc-core==7.3
      - pyobjc-framework-applescriptkit==7.3
      - pyobjc-framework-applescriptobjc==7.3
      - pyobjc-framework-avfoundation==7.3
      - pyobjc-framework-cocoa==7.3
      - pyobjc-framework-coremedia==7.3
      - pyobjc-framework-coreml==7.3
      - pyobjc-framework-coreservices==7.3
      - pyobjc-framework-fsevents==7.3
      - pyobjc-framework-metal==7.3
      - pyobjc-framework-photos==7.3
      - pyobjc-framework-quartz==7.3
      - pyobjc-framework-vision==7.3
      - pyrsistent==0.19.2
      - pytimeparse2==1.4.0
      - pyyaml==5.4.1
      - pyzmq==24.0.1
      - regex==2022.9.13
      - reloci==3
      - rich==12.5.1
      - rich-theme-manager==0.11.0
      - send2trash==1.8.0
      - shortuuid==1.0.9
      - sniffio==1.3.0
      - sortphotos==1.0
      - soupsieve==2.3.2.post1
      - stack-data==0.6.2
      - tenacity==8.0.1
      - terminado==0.17.1
      - testpath==0.6.0
      - textx==2.3.0
      - tinycss2==1.2.1
      - toml==0.10.2
      - tornado==6.2
      - traitlets==4.3.3
      - traittypes==0.2.1
      - wand==0.6.10
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.4.2
      - widgetsnbextension==3.6.1
      - wrapt==1.13.3
      - wurlitzer==2.1.1
      - xattr==0.9.9
      - xdg==5.1.1
      - zipp==3.11.0
